persistence true
persistence_location /mosquitto/data/
listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/data/passwordfile
user mosquitto
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
